### ISSUE TITLE
SRCSET

### ISSUE THREAD

**Issue by rpasillas** [Automattic/wpcom-thumbnail-editor#10]
This does not seem to work with the thumbnails that use srcset.

**Comment by sanketio** [comment]
Hello

We're also facing the same issue.

Images are getting cropped, the information is added to the database and is visible in `<img src ="">` but for some reason, it’s not getting added to the images `srcset="xxx"` (which then displays the newly cropped image). But it isn’t happening for all images and only for certain thumbnail sizes. We thought it might be an image upload size issue (image width/height too small) but there are very large images which aren’t displaying the cropped images either. It feels completely random.

Only worked on [single](https://splc-dev.mystagingwebsite.com/2018/08/secret-admin-searches/) and [News](https://splc-dev.mystagingwebsite.com/category/news/page/2/#post-35966) page (`dara-featured-image` thumbnail), but not in the slider on the [homepage](https://splc-dev.mystagingwebsite.com/)

This is the attachment URL - https://splc-dev.mystagingwebsite.com/wp-content/uploads/2018/08/searchslider-1.png - Dimensions: 1500 × 966

These are the variations:
1. thumbnail: 150×150 pixels (cropped to fit) searchslider-1-150x150.png
2. medium: 300×300 pixels (proportionally resized to fit inside dimensions) searchslider-1-300x193.png
3. medium_large: 768×0 pixels (proportionally resized to fit inside dimensions) searchslider-1-768x495.png
4. large: 1024×1024 pixels (proportionally resized to fit inside dimensions) searchslider-1-1024x659.png
5. dara-featured-image: 880×312 pixels (cropped to fit) searchslider-1-880x312.png
6. dara-hero-thumbnail: 1290×830 pixels (cropped to fit) searchslider-1-1290x830.png
7. dara-page-thumbnail: 1290×475 pixels (cropped to fit) searchslider-1-1290x475.png
8. dara-grid-thumbnail: 720×484 pixels (cropped to fit) searchslider-1-720x484.png
9. dara-testimonial-thumbnail: 180×180 pixels (cropped to fit) searchslider-1-180x180.png
10. jetpack-portfolio-admin-thumb: 50×50 pixels (cropped to fit) searchslider-1-50x50.png

**Note**: We’ve tried by disabling Jetpack’s image setting after that image crop worked fine, but with Jetpack as an image source, it is not working as expected. The problem is - it is random, most of the images are fine.

It could be an issue with Jetpack or more specifically, Photon. Or maybe we’re missing something completely obvious.

**Comment by dougaxe1** [comment]
I've come across this same issue. Because the plugin operates on the `image_downsize()` function, it only gets called for the main img src. `wp_calculate_image_srcset()` operates on image meta instead and lacks all crop parameters.

VIPs MU Plugin image handler operates on the `wp_get_attachment_metadata` instead. It would be a large refactor, but it could probably be made to work if operating from that perspective instead of image_downsize.

My workaround was to disable srcset until we can find a replacement solution.
